name: Build and Deploy

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build and deploy
        run: |
          git config --global user.email "jerebot@bot.io"
          git config --global user.name "jere-bot"
          git remote set-url origin https://${{ secrets.GH_USER }}:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.GH_USER }}/${{ secrets.GH_REPO }}
          npm install
          npm run deploy
